imports:
    - { resource: config_dev.yml }

liip_functional_test: ~

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname:   "%database_name%_test"

web_profiler:
    toolbar: false
    intercept_redirects: false

